/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': '#191c1e',
        'surface': '#f7f9fb',
        'secondary': '#712ae2',
        'inverse-on-surface': '#eff1f3',
        'on-secondary-container': '#fffbff',
        'primary-fixed-dim': '#bec6e0',
        'inverse-surface': '#2d3133',
        'inverse-primary': '#bec6e0',
        'error': '#ba1a1a',
        'primary-fixed': '#dae2fd',
        'surface-container': '#eceef0',
        'primary': '#000000',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'outline': '#76777d',
        'surface-variant': '#e0e3e5',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#38485d',
        'on-primary-fixed': '#131b2e',
        'on-primary-container': '#7c839b',
        'primary-container': '#131b2e',
        'on-tertiary-fixed': '#0b1c30',
        'on-tertiary-container': '#75859d',
        'tertiary-container': '#0b1c30',
        'surface-container-highest': '#e0e3e5',
        'surface-container-high': '#e6e8ea',
        'secondary-container': '#8a4cfc',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#d3e4fe',
        'surface-tint': '#565e74',
        'on-secondary-fixed-variant': '#5a00c6',
        'on-primary': '#ffffff',
        'outline-variant': '#c6c6cd',
        'secondary-fixed': '#eaddff',
        'on-primary-fixed-variant': '#3f465c',
        'on-secondary-fixed': '#25005a',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#b7c8e1',
        'tertiary': '#000000',
        'background': '#f7f9fb',
        'on-surface-variant': '#45464d',
        'secondary-fixed-dim': '#d2bbff',
        'on-background': '#191c1e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        headline: ['"Hanken Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0px 4px 20px rgba(15, 23, 42, 0.05)',
      },
    },
  },
  plugins: [],
}